language: node_js
cache:
  npm: false
matrix:
  include:
    - node_js: "node"
      env: CI=coverage
    - node_js: "8"
    - node_js: "10"
    - node_js: "11"

deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
notifications:
  email: false
after_success:
  - if [ "$CI" = "coverage" ]; then npm install coveralls --no-save && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi