name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.13.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm test
  test-for-old-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.10.x, 10.13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Downgrade stylelint
      run: |+
        npm install -D stylelint@13.6.1 ignore@5.1.8 globby@11.0.1 postcss@7.0.27 autoprefixer@9.7.4 mocha@7.1.1  --save-exact
        npx rimraf node_modules
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm test
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm run test:nyc
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
